#!/bin/bash

for alpha0 in $(seq 8 0.5 11); do
    for alpha1 in $(seq 0.2 0.1 0.6); do
        for beta in 0.001 0.005 0.01 0.02 0.05; do
            for factor_amp in 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15; do
                echo -ne "a0=$alpha0, a1=$alpha1, b=$beta:\t"
                scripts/run_vad.sh $alpha0 $alpha1 $beta | grep TOTAL
            done
        done
    done
done | sort -t: -k 3 -n -r
